import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConvexClientProvider } from "@/components/convex-client-provider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { JotaiProvaider } from "@/components/JotaiProvaider";
import { NuqsAdapter } from 'nuqs/adapters/next/app'




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <ConvexClientProvider>
            <JotaiProvaider>
              <NuqsAdapter>
                <AntdRegistry>
                  {children}
                </AntdRegistry>
              </NuqsAdapter>
            </JotaiProvaider>
          </ConvexClientProvider>

        </body>
      </html>
    </ConvexAuthNextjsServerProvider>

  );
}
